export const ON_REGIONAL_CONTENT = {
  nobulAddressLine1: "Nobul Corporation, Brokerage",
  nobulAddressLine2: "200 Wellington St W, Unit #310",
  nobulAddressLine3: "Toronto, ON M5V 3C7",
  listingTerms:
    "The listing information contained on this site is based in whole or in part on information that is provided by members of CREA, who are responsible for its accuracy. CREA reproduces and distributes this information as a service for its members and assumes no responsibility for its accuracy. The listing content on this website is intended soley for the private, non-commercial use by individuals. Any other reproduction, distribution or use of the content, in whole or in part, is specifically forbidden. The prohibited uses include commercial use, “screen scraping”, “database scraping”, and any other activity intended to collect, store, reorganize, or manipulate data on the pages produced by or displayed on this website.",
  trademarkTerms:
    "The trademarks REALTOR®, REALTORS®, and the REALTOR® logo are certification marks that are owned by REALTOR® Canada, Inc. and licensed exclusively to CREA. These certification marks identify real estate professionals who are members of CREA and who must abide by CREA's By-Laws, Rules, and the REALTOR® Code. The MLS® trademark and the MLS® logo are owned by CREA and identify the quality of services provided by real estate professionals who are members of CREA.",
  browseTermsAndConditionsPopup: `<p>This website is operated by a member of The Canadian Real Estate Association (CREA). The content on this website is owned or controlled by CREA. By accessing this website, the user agrees to be bound by these terms of use as amended from time to time, and agrees that these terms of use constitute a binding contract between the user, and CREA.</p><p>REALTOR®, REALTORS®, and the REALTOR® logo are certification marks that are owned by REALTOR® Canada Inc. and licensed exclusively to The Canadian Real Estate Association (CREA). These certification marks identify real estate professionals who are members of CREA and who must abide by CREA's By-Laws, Rules, and the REALTOR® Code. The MLS® trademark and the MLS® logo are owned by CREA and identify the professional real estate services provided by members of CREA</p><p>The information contained on this website is based in whole or in part on information that is provided by members of CREA, who are responsible for its accuracy. CREA reproduces and distributes this information as a service for its members, and assumes no responsibility for its completeness or accuracy.</p><p>We may at any time amend these Terms of Use by updating this posting. All users of this site are bound by these amendments should they wish to continue accessing the website, and should therefore periodically visit this page to review any and all such amendments</p>`
};
