# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
          - v1-npm-deps-

      - run: 
          name: Install Dependencies
          command: yarn install

      - save_cache: 
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules 
        
      # run tests!
      - run: 
          name: Jest Unit Test
          command: ./node_modules/.bin/jest --bail

      - run:
          name: Create dist folder
          command: NODE_ENV=development ./node_modules/.bin/webpack --config webpack.client.config.js

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN


