version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

    
  test:
    docker:
    # specify the version you desire here
    - image: circleci/node:8.11.3

    steps:
      - checkout

      # - run:
      #     name: "JavaScript Linter"
      #     # yarn here makes sure we are using the local jest binary
      #     command: yarn lint -- --format junit -o reports/junit/js-lint-results.xml

      # run tests!
      - run:
          name: "JavaScript Test Suite"
          # yarn here makes sure we are using the local jest binary
          command: yarn test -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit
          

  deploy:
    docker:
    # specify the version you desire here
    - image: circleci/node:8.11.3

    steps:
      - checkout

      - run:
          name: Create dist folder
          command: NODE_ENV=development ./node_modules/.bin/webpack --config webpack.client.config.js

      - run:
          name: Firebase Deploy
          command: |
            ./node_modules/.bin/firebase use nobul-edward
            ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test


