export const AGENT_RATING_IS_LOADING = "AGENT_RATING_IS_LOADING";
export const SAVE_AGENT_RATING_SUCCESS = "SAVE_AGENT_RATING_SUCCESS";
export const SAVE_AGENT_RATING_FAILURE = "SAVE_AGENT_RATING_FAILURE";
export const GET_AGENT_RATING_SUCCESS = "GET_AGENT_RATING_SUCCESS";
export const GET_AGENT_RATING_FAILURE = "GET_AGENT_RATING_FAILURE";
