export const TRIGGER_LOGIN_FOR_ANONYMOUS_USER =
  "TRIGGER_LOGIN_FOR_ANONYMOUS_USER";
export const SET_FAVORITE_FOR_ANONYMOUS_USER =
  "SET_FAVORITE_FOR_ANONYMOUS_USER";
export const OPEN_EVENT_CONFIRMATION_MODAL = "OPEN_EVENT_CONFIRMATION_MODAL";
export const CLOSE_EVENT_CONFIRMATION_MODAL = "CLOSE_EVENT_CONFIRMATION_MODAL";
export const OPEN_HOW_IT_WORKS_MODAL = "OPEN_HOW_IT_WORKS_MODAL";
export const CLOSE_HOW_IT_WORKS_MODAL = "CLOSE_HOW_IT_WORKS_MODAL";
