export const USERS_IS_LOADING = "USERS_IS_LOADING";
export const USERS_IS_LOADING_SUCCESS = "USERS_IS_LOADING_SUCCESS";
export const USERS_IS_LOADING_FAILURE = "USERS_IS_LOADING_FAILURE";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
export const GET_AGENT_SERVICES_SUCCESS = "GET_AGENT_SERVICES_SUCCESS";
export const GET_AGENT_SERVICES_FAILURE = "GET_AGENT_SERVICES_FAILURE";
export const GET_AGENT_COMMISSION_SUCCESS = "GET_AGENT_COMMISSION_SUCCESS";
export const GET_AGENT_COMMISSION_FAILURE = "GET_AGENT_COMMISSION_FAILURE";
export const GET_AGENT_AVERAGE_RATING_SUCCESS =
  "GET_AGENT_AVERAGE_RATING_SUCCESS";
export const GET_AGENT_AVERAGE_RATING_FAILURE =
  "GET_AGENT_AVERAGE_RATING_FAILURE";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const UPDATE_SERVICES_AND_COMMISSIONS =
  "UPDATE_SERVICES_AND_COMMISSIONS";
export const UPDATE_SERVICES_AND_COMMISSIONS_FAILURE =
  "UPDATE_SERVICES_AND_COMMISSIONS_FAILURE";
export const UPDATE_REGION_AND_PROPERTY_TYPE =
  "UPDATE_REGION_AND_PROPERTY_TYPE";
export const UPDATE_REGION_AND_PROPERTY_TYPE_FAILURE =
  "UPDATE_REGION_AND_PROPERTY_TYPE_FAILURE";
export const SET_USER_GEOLOCATION = "SET_USER_GEOLOCATION";
export const SET_PROPERTY_AS_FAVORITE_SUCCESS =
  "SET_PROPERTY_AS_FAVORITE_SUCCESS";
export const REMOVE_PROPERTY_AS_FAVORITE_SUCCESS =
  "REMOVE_PROPERTY_AS_FAVORITE_SUCCESS";
export const SET_PROPERTY_AS_FAVORITE_FAILURE =
  "SET_PROPERTY_AS_FAVORITE_FAILURE";
export const REMOVE_PROPERTY_AS_FAVORITE_FAILURE =
  "REMOVE_PROPERTY_AS_FAVORITE_FAILURE";
export const SET_USER_AVATAR_URL = "SET_USER_AVATAR_URL";
export const SET_USER_AVATAR_TYPE_SUCCESS = "SET_USER_AVATAR_TYPE_SUCCESS";
export const GET_USERS_FAVORITE_LISTINGS_SUCCESS =
  "GET_USERS_FAVORITE_LISTINGS_SUCCESS";
export const GET_USERS_FAVORITE_LISTINGS_FAILURE =
  "GET_USERS_FAVORITE_LISTINGS_FAILURE";
export const SET_REVERSE_GEOLOCATION_SUCCESS =
  "SET_REVERSE_GEOLOCATION_SUCCESS";
export const SET_REVERSE_GEOLOCATION_ERROR = "SET_REVERSE_GEOLOCATION_ERROR";
export const CLEAR_AUTH_ERROR_STATE = "CLEAR_AUTH_ERROR_STATE";
export const GET_USERS_AGREEMENT_STATUSES_SUCC =
  "GET_USERS_AGREEMENT_STATUSES_SUCC";
export const GET_USERS_AGREEMENT_STATUSES_FAIL =
  "GET_USERS_AGREEMENT_STATUSES_FAIL";
export const RESEND_VERIFICATION_EMAIL_SUCCESS =
  "RESEND_VERIFICATION_EMAIL_SUCCESS";
export const RESEND_VERIFICATION_EMAIL_FAIL = "RESEND_VERIFICATION_EMAIL_FAIL";
export const CLEAR_RESEND_VERIFICATION_STATUS =
  "CLEAR_RESEND_VERIFICATION_STATUS";
export const RELOAD_USER_LOADING = "RELOAD_USER_LOADING";
export const RELOAD_USER_SUCCESS = "RELOAD_USER_SUCCESS";
export const RELOAD_USER_FAILURE = "RELOAD_USER_FAILURE";
export const SET_FIRST_TIME_REGISTRATION_STATUS =
  "SET_FIRST_TIME_REGISTRATION_STATUS";
export const UPDATE_STANDARD_BUY_OFFER_SUCCESS =
  "UPDATE_STANDARD_BUY_OFFER_SUCCESS";
export const UPDATE_STANDARD_BUY_OFFER_FAILURE =
  "UPDATE_STANDARD_BUY_OFFER_FAILURE";
export const UPDATE_STANDARD_SELL_OFFER_SUCCESS =
  "UPDATE_STANDARD_SELL_OFFER_SUCCESS";
export const UPDATE_STANDARD_SELL_OFFER_FAILURE =
  "UPDATE_STANDARD_SELL_OFFER_FAILURE";
export const UPDATE_MARKETING_VALUE_USER_SUCCESS =
  "UPDATE_MARKETING_VALUE_USER_SUCCESS";
export const UPDATE_MARKETING_VALUE_USER_FAILURE =
  "UPDATE_MARKETING_VALUE_USER_FAILURE";
export const SET_STANDARD_PROPOSAL_SUCCESS = "SET_STANDARD_PROPOSAL_SUCCESS";
export const SET_STANDARD_PROPOSAL_FAILURE = "SET_STANDARD_PROPOSAL_FAILURE";
export const UPDATE_NOTIFICATION_SETTING_SUCCESS =
  "UPDATE_NOTIFICATION_SETTING_SUCCESS";
export const UPDATE_NOTIFICATION_SETTING_FAILURE =
  "UPDATE_NOTIFICATION_SETTING_FAILURE";
export const AUTOBIDS_IS_LOADING = "AUTOBIDS_IS_LOADING";
export const POST_AUTO_BIDS_SUCCESS = "POST_AUTO_BIDS_SUCCESS";
export const POST_AUTO_BIDS_FAILURE = "POST_AUTO_BIDS_FAILURE";
export const UPDATE_AUTO_BIDS_STATUS_FOR_BUYERS_SUCCESS =
  "UPDATE_AUTO_BIDS_STATUS_FOR_BUYERS_SUCCESS";
export const UPDATE_AUTO_BIDS_STATUS_FOR_SELLERS_SUCCESS =
  "UPDATE_AUTO_BIDS_STATUS_FOR_SELLERS_SUCCESS";
export const UPDATE_AUTO_BIDS_STATUS_FAILURE =
  "UPDATE_AUTO_BIDS_STATUS_FAILURE";
export const GET_AUTO_BIDS_STATUS_FOR_BUYERS_SUCCESS =
  "GET_AUTO_BIDS_STATUS_FOR_BUYERS_SUCCESS";
export const GET_AUTO_BIDS_STATUS_FOR_SELLERS_SUCCESS =
  "GET_AUTO_BIDS_STATUS_FOR_SELLERS_SUCCESS";
export const GET_AUTO_BIDS_STATUS_FAILURE = "GET_AUTO_BIDS_STATUS_FAILURE";
export const UPDATE_CURRENT_USER_REGIONS_SUCCESS =
  "UPDATE_CURRENT_USER_REGIONS_SUCCESS";
export const UPDATE_CURRENT_USER_REGIONS_FAILURE =
  "UPDATE_CURRENT_USER_REGIONS_FAILURE";
export const ADD_VERIFICATION_DATA_SUCCESS = "ADD_VERIFICATION_DATA_SUCCESS";
export const ADD_VERIFICATION_DATA_FAILURE = "ADD_VERIFICATION_DATA_FAILURE";
export const GET_LICENSE_IMAGE_URL_SUCCESS = "GET_LICENSE_IMAGE_URL_SUCCESS";
export const SET_USER_AVATAR_ERROR = "SET_USER_AVATAR_ERROR";
export const SET_USER_AVATAR_TYPE_ERROR = "SET_USER_AVATAR_TYPE_ERROR";
export const GET_USER_LICENSE_IMAGE_FAILURE = "GET_USER_LICENSE_IMAGE_FAILURE";
export const UPDATE_CURRENT_USER_LICENSE_IMAGE_MOBILE_SUCCESS =
  "UPDATE_CURRENT_USER_LICENSE_IMAGE_MOBILE_SUCCESS";
export const UPDATE_CURRENT_USER_LICENSE_IMAGE_MOBILE_FAILURE =
  "UPDATE_CURRENT_USER_LICENSE_IMAGE_MOBILE_FAILURE";
export const UPDATE_AUTO_BIDS_FOR_BUYERS_SUCCESS =
  "UPDATE_AUTO_BIDS_FOR_BUYERS_SUCCESS";
export const UPDATE_AUTO_BIDS_FOR_SELLERS_SUCCESS =
  "UPDATE_AUTO_BIDS_FOR_SELLERS_SUCCESS";
