export const SAVE_CURRENT_LISTING_LIST = "SAVE_CURRENT_LISTING_LIST";
export const CLEAR_CURRENT_LISTING_LIST = "CLEAR_CURRENT_LISTING_LIST";
export const SET_BROWSE_LOCATION = "SET_BROWSE_LOCATION";
