export const BUY_AUTOBID_SET_REGIONS = "BUY_AUTOBID_SET_REGIONS";
export const BUY_AUTOBID_SET_SERVICES = "BUY_AUTOBID_SET_SERVICES";
export const BUY_AUTOBID_SET_PRICE_RANGE_LOW =
  "BUY_AUTOBID_SET_PRICE_RANGE_LOW";
export const BUY_AUTOBID_SET_PRICE_RANGE_HIGH =
  "BUY_AUTOBID_SET_PRICE_RANGE_HIGH";
export const BUY_AUTOBID_SET_REBATE_PERCENT = "BUY_AUTOBID_SET_REBATE_PERCENT";
export const BUY_AUTOBID_SET_TAGLINE = "BUY_AUTOBID_SET_TAGLINE";
export const BUY_AUTOBID_SET_MESSAGE = "BUY_AUTOBID_SET_MESSAGE";
export const BUY_AUTOBID_CLEAR = "BUY_AUTOBID_CLEAR";
