export const BUY_STANDARD_PROPOSAL_SET_REGIONS =
  "BUY_STANDARD_PROPOSAL_SET_REGIONS";
export const BUY_STANDARD_PROPOSAL_SET_SERVICES =
  "BUY_STANDARD_PROPOSAL_SET_SERVICES";
export const BUY_STANDARD_PROPOSAL_SET_REBATE_PERCENT =
  "BUY_STANDARD_PROPOSAL_SET_REBATE_PERCENT";
export const BUY_STANDARD_PROPOSAL_SET_TAGLINE =
  "BUY_STANDARD_PROPOSAL_SET_TAGLINE";
export const BUY_STANDARD_PROPOSAL_SET_MESSAGE =
  "BUY_STANDARD_PROPOSAL_SET_MESSAGE";
export const SET_MARKETPLACE_PROPOSAL_FLOW = "SET_MARKETPLACE_PROPOSAL_FLOW";
export const CLEAR_BUY_STANDARD_PROPOSAL = "CLEAR_BUY_STANDARD_PROPOSAL";
export const CLEAR_MARKETPLACE_PROPOSAL_FLOW =
  "CLEAR_MARKETPLACE_PROPOSAL_FLOW";
