export const EVENTS_IS_LOADING = "EVENTS_IS_LOADING";
export const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS";
export const POST_EVENT_FAILURE = "POST_EVENT_FAILURE";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";
export const ACCEPT_EVENT_SUCCESS = "ACCEPT_EVENT_SUCCESS";
export const ACCEPT_EVENT_FAILURE = "ACCEPT_EVENT_FAILURE";
export const DECLINE_EVENT_SUCCESS = "DECLINE_EVENT_SUCCESS";
export const DECLINE_EVENT_FAILURE = "DECLINE_EVENT_FAILURE";
export const PROPOSED_NEW_TIME_SUCCESS = "PROPOSED_NEW_TIME_SUCCESS";
export const PROPOSED_NEW_TIME_FAILURE = "PROPOSED_NEW_TIME_FAILURE";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const SET_EVENT_INVISIBLE_FAILURE = "SET_EVENT_INVISIBLE_FAILURE";
export const SET_EVENT_INVISIBLE_SUCCESS = "SET_EVENT_INVISIBLE_SUCCESS";
export const GET_EVENT_CREATED_AT_RANGE_SUCCESS =
  "GET_EVENT_CREATED_AT_RANGE_SUCCESS";
export const GET_EVENT_CREATED_AT_RANGE_FAILURE =
  "GET_EVENT_CREATED_AT_RANGE_FAILURE";
