export const JOBS_IS_LOADING = "JOBS_IS_LOADING";
export const GET_ALL_BUY_JOBS_SUCCESS = "GET_ALL_BUY_JOBS_SUCCESS";
export const GET_ALL_BUY_JOBS_FAILURE = "GET_ALL_BUY_JOBS_FAILURE";
export const GET_ALL_CONSUMER_BUY_JOBS_SUCCESS =
  "GET_ALL_CONSUMER_BUY_JOBS_SUCCESS";
export const GET_ALL_CONSUMER_BUY_JOBS_FAILURE =
  "GET_ALL_CONSUMER_BUY_JOBS_FAILURE";
export const GET_ALL_CONSUMER_SELL_JOBS_SUCCESS =
  "GET_ALL_CONSUMER_SELL_JOBS_SUCCESS";
export const GET_ALL_CONSUMER_SELL_JOBS_FAILURE =
  "GET_ALL_CONSUMER_SELL_JOBS_FAILURE";
export const GET_ALL_CONSUMER_DRAFT_JOBS_SUCCESS =
  "GET_ALL_CONSUMER_DRAFT_JOBS_SUCCESS";
export const GET_ALL_CONSUMER_DRAFT_JOBS_FAILURE =
  "GET_ALL_CONSUMER_DRAFT_JOBS_FAILURE";
export const GET_ALL_CONSUMER_PENDING_JOBS_SUCCESS =
  "GET_ALL_CONSUMER_PENDING_JOBS_SUCCESS";
export const GET_ALL_CONSUMER_PENDING_JOBS_FAILURE =
  "GET_ALL_CONSUMER_PENDING_JOBS_FAILURE";
export const GET_ALL_SELL_JOBS_SUCCESS = "GET_ALL_SELL_JOBS_SUCCESS";
export const GET_ALL_SELL_JOBS_FAILURE = "GET_ALL_SELL_JOBS_FAILURE";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAILURE = "UPDATE_JOB_FAILURE";
export const SAVE_JOB_SUCCESS = "SAVE_JOB_SUCCESS";
export const SAVE_JOB_FAILURE = "SAVE_JOB_FAILURE";
export const FILTER_JOBS = "FILTER_JOBS";
export const GET_JOB_DETAIL_SUCCESS = "GET_JOB_DETAIL_SUCCESS";
export const GET_JOB_DETAIL_FAILURE = "GET_JOB_DETAIL_FAILURE";
export const TAG_LISTING_TO_JOB_SUCCESS = "TAG_LISTING_TO_JOB_SUCCESS";
export const TAG_LISTING_TO_JOB_FAILURE = "TAG_LISTING_TO_JOB_FAILURE";
export const REMOVE_TAGGED_LISTING_FROM_JOB_SUCCESS =
  "REMOVE_TAG_LISTING_FROM_JOB_SUCCESS";
export const REMOVE_TAGGED_LISTING_FROM_JOB_FAILURE =
  "REMOVE_TAG_LISTING_FROM_JOB_FAILURE";
export const GET_ALL_REGION_JOBS_SUCCESS = "GET_ALL_REGION_JOBS_SUCCESS";
export const GET_ALL_REGION_JOBS_FAILURE = "GET_ALL_REGION_JOBS_FAILURE";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAILURE = "DELETE_JOB_FAILURE";
export const APPEND_JOB_SUCCESS = "APPEND_JOB_SUCCESS";
export const APPEND_JOB_FAILURE = "APPEND_JOB_FAILURE";
export const APPEND_JOBS_SUCCESS = "APPEND_JOBS_SUCCESS";
export const APPEND_JOBS_FAILURE = "APPEND_JOBS_FAILURE";
export const GET_JOBS_CREATED_AT_RANGE_SUCCESS =
  "GET_JOBS_CREATED_AT_RANGE_SUCCESS";
export const GET_JOBS_CREATED_AT_RANGE_FAILURE =
  "GET_JOBS_CREATED_AT_RANGE_FAILURE";
export const SET_MARKETPLACE_JOB_FILTERS = "SET_MARKETPLACE_JOB_FILTERS";
export const GET_MULTIPLE_MARKETPLACE_JOBS_SUCCESS =
  "GET_MULTIPLE_MARKETPLACE_JOBS_SUCCESS";
export const GET_MULTIPLE_MARKETPLACE_JOBS_FAILURE =
  "GET_MULTIPLE_MARKETPLACE_JOBS_FAILURE";
export const SET_TEMPORARY_MARKETPLACE_REGIONS =
  "SET_TEMPORARY_MARKETPLACE_REGIONS";
