export const LISTINGS_IS_LOADING = "LISTINGS_IS_LOADING";
export const MASTERLIST_IS_LOADING = "MASTERLIST_IS_LOADING";
export const GET_MASTERLIST_SUCCESS = "GET_MASTERLIST_SUCCESS";
export const GET_MASTERLIST_FAILURE = "GET_MASTERLIST_FAILURE";
export const GET_SINGLE_LISTING_DETAILS_SUCCESS =
  "GET_SINGLE_LISTING_DETAILS_SUCCESS";
export const GET_SINGLE_LISTING_DETAILS_FAILURE =
  "GET_SINGLE_LISTING_DETAILS_FAILURE";
export const GET_MULTIPLE_LISTING_DETAILS_SUCCESS =
  "GET_MULTIPLE_LISTING_DETAILS_SUCCESS";
export const GET_MULTIPLE_LISTING_DETAILS_FAILURE =
  "GET_MULTIPLE_LISTING_DETAILS_FAILURE";
export const GET_DETAILS_AND_FEATURE_IMAGES_SUCCESS =
  "GET_DETAILS_AND_FEATURE_IMAGES_SUCCESS";
export const GET_DETAILS_AND_FEATURE_IMAGES_FAILURE =
  "GET_DETAILS_AND_FEATURE_IMAGES_FAILURE";
export const FILTER_LISTINGS = "FILTER_LISTINGS";
export const GET_FAVORITE_LISTINGS_DETAILS_SUCCESS =
  "GET_FAVORITE_LISTINGS_DETAILS_SUCCESS";
export const GET_FAVORITE_LISTINGS_DETAILS_FAILURE =
  "GET_FAVORITE_LISTINGS_DETAILS_FAILURE";
export const GET_TAGGED_LISTINGS_DETAILS_SUCCESS =
  "GET_TAGGED_LISTINGS_DETAILS_SUCCESS";
export const GET_TAGGED_LISTINGS_DETAILS_FAILURE =
  "GET_TAGGED_LISTINGS_DETAILS_FAILURE";
export const SORT_LISTINGS_IDS_SUCCESS = "SORT_LISTINGS_IDS_SUCCESS";
export const SORT_LISTINGS_IDS_FAILURE = "SORT_LISTINGS_IDS_FAILURE";
export const SORT_LISTINGS_IDS_LOADING = "SORT_LISTINGS_IDS_LOADING";
