export const OFFERS_IS_LOADING = "OFFERS_IS_LOADING";
export const GET_JOB_OFFERS_SUCCESS = "GET_JOB_OFFERS_SUCCESS";
export const GET_JOB_OFFERS_FAILURE = "GET_JOB_OFFERS_FAILURE";
export const GET_CONSUMER_BUY_OFFERS_SUCCESS =
  "GET_CONSUMER_BUY_OFFERS_SUCCESS";
export const GET_CONSUMER_SELL_OFFERS_SUCCESS =
  "GET_CONSUMER_SELL_OFFERS_SUCCESS";
export const GET_CONSUMER_BUY_OFFERS_FAILURE =
  "GET_CONSUMER_BUY_OFFERS_FAILURE";
export const GET_CONSUMER_SELL_OFFERS_FAILURE =
  "GET_CONSUMER_SELL_OFFERS_FAILURE";
export const GET_AGENT_BUY_OFFERS_SUCCESS = "GET_ALL_BUY_OFFERS_SUCCESS";
export const GET_AGENT_BUY_OFFERS_FAILURE = "GET_ALL_BUY_OFFERS_FAILURE";
export const GET_AGENT_SELL_OFFERS_SUCCESS = "GET_ALL_SELL_OFFERS_SUCCESS";
export const GET_AGENT_SELL_OFFERS_FAILURE = "GET_ALL_SELL_OFFERS_FAILURE";
export const GET_AGENT_AUTOBID_OFFERS_SUCCESS =
  "GET_AGENT_AUTOBID_OFFERS_SUCCESS";
export const GET_AGENT_AUTOBID_OFFERS_FAILURE =
  "GET_AGENT_AUTOBID_OFFERS_FAILURE";
export const GET_OFFER_DETAIL_SUCCESS = "GET_OFFER_DETAIL_SUCCESS";
export const GET_OFFER_DETAIL_FAILURE = "GET_OFFER_DETAIL_FAILURE";
export const GET_JOB_WINNING_OFFER_SUCCESS = "GET_JOB_WINNING_OFFER_SUCCESS";
export const GET_JOB_WINNING_OFFER_FAILURE = "GET_JOB_WINNING_OFFER_FAILURE";
export const SAVE_OFFER_SUCCESS = "SAVE_OFFER_SUCCESS";
export const SAVE_OFFER_FAILURE = "SAVE_OFFER_FAILURE";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
export const ACCEPT_OFFER_FAILURE = "ACCEPT_OFFER_FAILURE";
export const REJECT_OFFER_SUCCESS = "REJECT_OFFER_SUCCESS";
export const REJECT_OFFER_FAILURE = "REJECT_OFFER_FAILURE";
export const WITHDRAW_OFFER_SUCCESS = "WITHDRAW_OFFER_SUCCESS";
export const WITHDRAW_OFFER_FAILURE = "WITHDRAW_OFFER_FAILURE";
export const PROMOTE_OFFER_SUCCESS = "PROMOTE_OFFER_SUCCESS";
export const PROMOTE_OFFER_FAILURE = "PROMOTE_OFFER_FAILURE";
export const SET_OFFER_HAS_BEEN_READ_SUCCESS =
  "SET_OFFER_HAS_BEEN_READ_SUCCESS";
export const SET_OFFER_HAS_BEEN_READ_FAILURE =
  "SET_OFFER_HAS_BEEN_READ_FAILURE";
export const SET_FAVORITE_OFFER_SUCCESS = "SET_FAVORITE_OFFER_SUCCESS";
export const SET_FAVORITE_OFFER_FAILURE = "SET_FAVORITE_OFFER_FAILURE";
export const CLEAR_WINNING_OFFER = "CLEAR_WINNING_OFFER";
export const SET_OFFERS_FILTERS = "SET_OFFERS_FILTERS";
export const FETCH_OFFER_SUCCESS = "FETCH_OFFER_SUCCESS";
export const FETCH_OFFER_FAILURE = "FETCH_OFFER_FAILURE";
export const GET_AGENT_TO_CONTRACT_SELL_OFFERS_SUCCESS =
  "GET_AGENT_TO_CONTRACT_SELL_OFFERS_SUCCESS";
export const GET_AGENT_TO_CONTRACT_BUY_OFFERS_SUCCESS =
  "GET_AGENT_TO_CONTRACT_BUY_OFFERS_SUCCESS";
export const CLEAR_SELL_OFFERS = "CLEAR_SELL_OFFERS";
export const CLEAR_BUY_OFFERS = "CLEAR_BUY_OFFERS";
export const GET_OFFERS_CREATED_AT_RANGE_SUCCESS =
  "GET_OFFERS_CREATED_AT_RANGE_SUCCESS";
export const GET_OFFERS_CREATED_AT_RANGE_FAILURE =
  "GET_OFFERS_CREATED_AT_RANGE_FAILURE";
//__________________________________________

// TODO:
// check if these are being used
export const GET_WINNING_OFFER_SUCCESS = "GET_WINNING_OFFER_SUCCESS";
export const GET_WINNING_OFFER_FAILURE = "GET_WINNING_OFFER_FAILURE";
export const EDIT_BUY_OFFER_SUCCESS = "EDIT_BUY_OFFER_SUCCESS";
export const EDIT_BUY_OFFER_FAILURE = "EDIT_BUY_OFFER_FAILURE";
export const EDIT_SELL_OFFER_SUCCESS = "EDIT_SELL_OFFER_SUCCESS";
export const EDIT_SELL_OFFER_FAILURE = "EDIT_SELL_OFFER_FAILURE";
export const UPDATE_BUY_OFFER_SUCCESS = "UPDATE_BUY_OFFER_SUCCESS";
export const UPDATE_BUY_OFFER_FAILURE = "UPDATE_BUY_OFFER_FAILURE";
export const UPDATE_SELL_OFFER_SUCCESS = "UPDATE_SELL_OFFER_SUCCESS";
export const UPDATE_SELL_OFFER_FAILURE = "UPDATE_SELL_OFFER_FAILURE";
