export const POLYGONS_IS_LOADING = "POLYGONS_IS_LOADING";
export const GET_POLYGONS_SUCCESS = "GET_POLYGONS_SUCCESS";
export const GET_POLYGONS_FAILURE = "GET_POLYGONS_FAILURE";
export const GET_SUPPORTED_BROWSE_POLYGONS_SUCCESS =
  "GET_SUPPORTED_BROWSE_POLYGONS_SUCCESS";
export const GET_SUPPORTED_BROWSE_POLYGONS_FAILURE =
  "GET_SUPPORTED_BROWSE_POLYGONS_FAILURE";
