export const SELL_STANDARD_PROPOSAL_SET_REGIONS =
  "SELL_STANDARD_PROPOSAL_SET_REGIONS";
export const SELL_STANDARD_PROPOSAL_SET_SERVICES =
  "SELL_STANDARD_PROPOSAL_SET_SERVICES";
export const SELL_STANDARD_PROPOSAL_SET_BROKERAGE_COMMISSION =
  "SELL_STANDARD_PROPOSAL_SET_BROKERAGE_COMMISSION";
export const SELL_STANDARD_PROPOSAL_SET_LISTING_COMMISSION =
  "SELL_STANDARD_PROPOSAL_SET_LISTING_COMMISSION";
export const SELL_STANDARD_PROPOSAL_SET_TAGLINE =
  "SELL_STANDARD_PROPOSAL_SET_TAGLINE";
export const SELL_STANDARD_PROPOSAL_SET_MESSAGE =
  "SELL_STANDARD_PROPOSAL_SET_MESSAGE";
export const CLEAR_SELL_STANDARD_PROPOSAL = "CLEAR_SELL_STANDARD_PROPOSAL";
