export const SELL_AUTOBID_SET_REGIONS = "SELL_AUTOBID_SET_REGIONS";
export const SELL_AUTOBID_SET_SERVICES = "SELL_AUTOBID_SET_SERVICES";
export const SELL_AUTOBID_SET_PRICE_RANGE_LOW =
  "SELL_AUTOBID_SET_PRICE_RANGE_LOW";
export const SELL_AUTOBID_SET_PRICE_RANGE_HIGH =
  "SELL_AUTOBID_SET_PRICE_RANGE_HIGH";
export const SELL_AUTOBID_SET_BROKERAGE_COMMISSION =
  "SELL_AUTOBID_SET_BROKERAGE_COMMISSION";
export const SELL_AUTOBID_SET_LISTING_COMMISSION =
  "SELL_AUTOBID_SET_LISTING_COMMISSION";
export const SELL_AUTOBID_SET_TAGLINE = "SELL_AUTOBID_SET_TAGLINE";
export const SELL_AUTOBID_SET_MESSAGE = "SELL_AUTOBID_SET_MESSAGE";
export const SELL_AUTOBID_CLEAR = "SELL_AUTOBID_CLEAR";
