export const STRIPE_CUSTOMERS_IS_LOADING = "STRIPE_CUSTOMERS_IS_LOADING";
export const POST_STRIPE_TOKEN_SUCCESS = "POST_STRIPE_TOKEN_SUCCESS";
export const POST_STRIPE_TOKEN_FAILURE = "POST_STRIPE_TOKEN_FAILURE";
export const GET_STRIPE_CUSTOMER_SUCCESS = "GET_STRIPE_CUSTOMER_SUCCESS";
export const GET_STRIPE_CUSTOMER_FAILURE = "GET_STRIPE_CUSTOMER_FAILURE";
export const GET_STRIPE_CARDS_SUCCESS = "GET_STRIPE_CARDS_SUCCESS";
export const GET_STRIPE_CARDS_FAILURE = "GET_STRIPE_CARDS_FAILURE";
export const HIDE_NEW_CARD = "HIDE_NEW_CARD";
export const SHOW_NEW_CARD = "SHOW_NEW_CARD";
export const UNSUBSCRIBE_FROM_STRIPE_PLAN_SUCCESS =
  "UNSUBSCRIBE_FROM_STRIPE_PLAN_SUCCESS";
export const UNSUBSCRIBE_FROM_STRIPE_PLAN_FAILURE =
  "UNSUBSCRIBE_FROM_STRIPE_PLAN_FAILURE";
export const CREATE_STRIPE_SINGLE_CHARGE_SUCCESS =
  "CREATE_STRIPE_SINGLE_CHARGE_SUCCESS";
export const CREATE_STRIPE_SINGLE_CHARGE_FAILURE =
  "CREATE_STRIPE_SINGLE_CHARGE_FAILURE";
export const CREATE_STRIPE_SUBSCRIPTION_CHARGE_SUCCESS =
  "CREATE_STRIPE_SUBSCRIPTION_CHARGE_SUCCESS";
export const CREATE_STRIPE_SUBSCRIPTION_CHARGE_FAILURE =
  "CREATE_STRIPE_SUBSCRIPTION_CHARGE_FAILURE";
export const GET_STRIPE_SUBSCRIPTION_ID_SUCCESS =
  "GET_STRIPE_SUBSCRIPTION_ID_SUCCESS";
export const GET_STRIPE_SUBSCRIPTION_ID_FAILURE =
  "GET_STRIPE_SUBSCRIPTION_ID_FAILURE";
export const GET_STRIPE_USER_SUBSCRIPTION_DATA_SUCCESS =
  "GET_STRIPE_USER_SUBSCRIPTION_DATA_SUCCESS";
export const GET_STRIPE_USER_SUBSCRIPTION_DATA_FAILURE =
  "GET_STRIPE_USER_SUBSCRIPTION_DATA_FAILURE";
export const GET_STRIPE_MONTHLY_SUBSCRIPTION_DATA_SUCCESS =
  "GET_STRIPE_MONTHLY_SUBSCRIPTION_DATA_SUCCESS";
export const GET_STRIPE_MONTHLY_SUBSCRIPTION_DATA_FAILURE =
  "GET_STRIPE_MONTHLY_SUBSCRIPTION_DATA_FAILURE";
