export const GET_CONSUMER_PROFILE_SUCCESS = "GET_CONSUMER_PROFILE_SUCCESS";
export const GET_CONSUMER_PROFILE_FAILURE = "GET_CONSUMER_PROFILE_FAILURE";
export const GET_AGENT_PROFILE_SUCCESS = "GET_AGENT_PROFILE_SUCCESS";
export const GET_AGENT_PROFILE_FAILURE = "GET_AGENT_PROFILE_FAILURE";
export const GET_MULTIPLE_AGENTS_SUCCESS = "GET_MULTIPLE_AGENTS_SUCCESS";
export const GET_MULTIPLE_AGENTS_FAILURE = "GET_MULTIPLE_AGENTS_FAILURE";
export const AGENTS_IS_LOADING = "AGENTS_IS_LOADING";
export const GET_MULTIPLE_AGENTS_WITH_AVATAR_SUCCESS =
  "GET_MULTIPLE_AGENTS_WITH_AVATAR_SUCCESS";
export const GET_MULTIPLE_AGENTS_WITH_AVATAR_FAILURE =
  "GET_MULTIPLE_AGENTS_WITH_AVATAR_FAILURE";
export const GET_AGENT_WITH_AVATAR_SUCCESS = "GET_AGENT_WITH_AVATAR_SUCCESS";
export const GET_AGENT_WITH_AVATAR_FAILURE = "GET_AGENT_WITH_AVATAR_FAILURE";
export const USER_PROFILE_IS_LOADING = "USER_PROFILE_IS_LOADING";
export const GET_MULTIPLE_CONSUMERS_SUCCESS = "GET_MULTIPLE_CONSUMERS_SUCCESS";
export const GET_MULTIPLE_CONSUMERS_FAILURE = "GET_MULTIPLE_CONSUMERS_FAILURE";
export const CONSUMERS_IS_LOADING = "CONSUMERS_IS_LOADING";
export const SET_CONSUMER_AVATAR_SUCCESS = "SET_CONSUMER_AVATAR_SUCCESS";
export const SET_CONSUMER_AVATAR_FAILURE = "SET_CONSUMER_AVATAR_FAILURE";
export const UPDATE_AGENT_AVATAR_SUCCESS = "UPDATE_AGENT_AVATAR_SUCCESS";
export const UPDATE_AGENT_AVATAR_FAILURE = "UPDATE_AGENT_AVATAR_FAILURE";
export const GET_USER_CREATED_AT_RANGE_SUCCESS =
  "GET_USER_CREATED_AT_RANGE_SUCCESS";
export const GET_USER_CREATED_AT_RANGE_FAILURE =
  "GET_USER_CREATED_AT_RANGE_FAILURE";
